name: Compile the slides (noanim)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
            lfs: true

      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master
        with:
            remote: true

      - name: Compile the main document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: noanim-eidi-tutorium-rep.tex
          latexmk_shell_escape: true
          pre_compile: "find \"sopra-collection/\" \\( -name '*.sty' -o -name '*.cls' \\) -type f -print0 | xargs -0 -I '{}' cp '{}' \"./\" && cp -r sopra-collection/sopra-listings/Languages ./Languages"

      - name: Commit PDF
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          cp noanim-eidi-tutorium-rep.pdf slides-eidi-rep.pdf
          git add -f slides-eidi-rep.pdf
          git commit -m "Update PDF by workflow"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: "gh-pages"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true

