name: Compile all slides

'on':
  push:
    branches:
    - master
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout git repository
      uses: actions/checkout@v2
      with:
        lfs: true
        submodules: true
    - name: Setup Python environment for sltx
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Setup and run sltx-install (and pu)
      run: |
        sudo apt install poppler-utils
        pip install six sltx
        echo "tx-default" | sltx docker
    - name: Compile the Documents
      run: |
        sltx compile --root --profile "tx-default"
    - name: Generate previews
      run: |
        cp noanim-eidi-tutorium-rep.pdf slides-eidi-rep.pdf
        cp eidi-tutorium-rep.pdf animated-eidi-rep.pdf
        cp noanim-short-eidi-tutorium-rep.pdf short-slides-eidi-rep.pdf
        cp short-eidi-tutorium-rep.pdf short-animated-eidi-rep.pdf
        pdftoppm -png -f 1 -l 1 ./noanim-eidi-tutorium-rep.pdf preview
    - name: Commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -f "slides-eidi-rep.pdf" "animated-eidi-rep.pdf" "short-slides-eidi-rep.pdf" "short-animated-eidi-rep.pdf" "preview-001.png"
        git commit -m "Full recompilation"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
