name: Compile all slides

'on':
  push:
    branches:
    - master
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout git repository
      uses: actions/checkout@v2
      with:
        lfs: true
        submodules: true
# https://github.com/actions/cache/issues/342
    - name: Caching
      id: cache-documentation
      uses: actions/cache@v3
      with:
        path: |
          build
          sub_*
        key: ${{ runner.os }}-eidi-pseudo-rep20-${{ github.run_id }}
        restore-keys: ${{ runner.os }}-eidi-pseudo-rep20-
    - name: Install PU for previews
      run: sudo apt install poppler-utils
    - name: Compile the Documentation, showcase and minimal
      uses: xu-cheng/latex-action@v2
      with:
        root_file: |
          eidi-tutorium-rep.tex
          noanim-eidi-tutorium-rep.tex
          short-eidi-tutorium-rep.tex
          noanim-short-eidi-tutorium-rep.tex
    - name: Generate previews
      run: |
        cp build/noanim-eidi-tutorium-rep.pdf slides-eidi-rep.pdf
        cp build/eidi-tutorium-rep.pdf animated-eidi-rep.pdf
        cp build/noanim-short-eidi-tutorium-rep.pdf short-slides-eidi-rep.pdf
        cp build/short-eidi-tutorium-rep.pdf short-animated-eidi-rep.pdf
        pdftoppm -png -f 1 -l 1 ./build/noanim-eidi-tutorium-rep.pdf preview
    - name: Commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -f "slides-eidi-rep.pdf" "animated-eidi-rep.pdf" "short-slides-eidi-rep.pdf" "short-animated-eidi-rep.pdf" "preview-001.png"
        git commit -m "Full recompilation"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
